// API calls
const rootURL = 'http://localhost:9000';
export const api = {
  getLootableCards: rootURL + '/api/lootable-cards',
  getPlayers: rootURL + '/api/players',
  markCardLooted: rootURL + '/api/cards/mark-looted',
  markCardSold: rootURL + '/api/cards/mark-sold',
  updateDatabase: rootURL + '/api/cards/update-images',
};

// Tier select options
export const rolls = [
  { id: 'T1', name: 'T1' },
  { id: 'T1+', name: 'T1+' },
  { id: 'T2', name: 'T2' },
  { id: 'T2+', name: 'T2+' },
  { id: 'T3', name: 'T3' },
  { id: 'T3+', name: 'T3+' },
  { id: 'T4', name: 'T4' },
  { id: 'T4+', name: 'T4+' },
];

// Faction options
export const factions = [
  { id: 'Basic', name: 'Basic' },
  { id: 'Protection', name: 'Protection' },
  { id: 'Leadership', name: 'Leadership' },
  { id: 'Aggression', name: 'Aggression' },
  { id: 'Justice', name: 'Justice' },
  { id: 'Your Choice', name: 'Your Choice' },
];

// Primary loot table rolls
export const lootTable = [
  {
    roll: 'T1',
    results: [
      'None',
      'None',
      'None',
      'None',
      'Tier C Basic',
      'Tier C Basic',
      'Tier C Basic',
      'Tier C Basic',
      'Tier C Basic',
      'Tier C Basic',
      'Tier B Roll',
      'Tier B Roll',
    ],
  },
  {
    roll: 'T1+',
    results: [
      'None',
      'Tier C Basic',
      'Tier C Basic',
      'Tier C Basic',
      'Tier C Basic',
      'Tier C Basic',
      'Tier C Basic',
      'Tier B Roll',
      'Tier B Roll',
      'Tier B Roll',
      'Tier B Roll',
      'Tier A Roll',
    ],
  },
  {
    roll: 'T2',
    results: [
      'Tier C Basic',
      'Tier C Basic',
      'Tier C Basic',
      'Tier C Basic',
      'Tier B Roll',
      'Tier B Roll',
      'Tier B Roll',
      'Tier B Roll',
      'Tier B Roll',
      'Tier B Roll',
      'Tier A Roll',
      'Tier A Roll',
    ],
  },
  {
    roll: 'T2+',
    results: [
      'Tier C Basic',
      'Tier B Roll',
      'Tier B Roll',
      'Tier B Roll',
      'Tier B Roll',
      'Tier B Roll',
      'Tier B Roll',
      'Tier A Roll',
      'Tier A Roll',
      'Tier A Roll',
      'Tier A Roll',
      'Tier S Roll',
    ],
  },
  {
    roll: 'T3',
    results: [
      'Tier B Roll',
      'Tier B Roll',
      'Tier B Roll',
      'Tier B Roll',
      'Tier A Roll',
      'Tier A Roll',
      'Tier A Roll',
      'Tier A Roll',
      'Tier A Roll',
      'Tier A Roll',
      'Tier S Roll',
      'Tier S Roll',
    ],
  },
  {
    roll: 'T3+',
    results: [
      'Tier A Roll',
      'Tier A Roll',
      'Tier A Roll',
      'Tier A Roll',
      'Tier A Roll',
      'Tier A Roll',
      'Tier A Roll',
      'Tier A Roll',
      'Tier S Roll',
      'Tier S Roll',
      'Tier S Roll',
      'Tier S Roll',
    ],
  },
  {
    roll: 'T4',
    results: [
      'Tier A Roll',
      'Tier A Roll',
      'Tier A Roll',
      'Tier A Roll',
      'Tier S Roll',
      'Tier S Roll',
      'Tier S Roll',
      'Tier S Roll',
      'Tier S Roll',
      'Tier S Roll',
      'Tier S Roll',
      'Shawarma',
    ],
  },
  {
    roll: 'T4+',
    results: [
      'Tier S Roll',
      'Tier S Roll',
      'Tier S Roll',
      'Tier S Roll',
      'Tier S Roll',
      'Tier S Roll',
      'Tier S Roll',
      'Tier S Roll',
      'Tier S Roll',
      'Tier S Roll',
      'Shawarma',
      'Shawarma',
    ],
  },
];
