// API calls
const rootURL = 'http://localhost:9000';
export const api = {
  getCards: rootURL + '/api/cards',
  getPlayers: rootURL + '/api/players',
  markLooted: rootURL + '/api/cards/mark-looted',
  markSold: rootURL + '/api/cards/mark-sold',
};

// Tier select options
export const tiers = [
  { id: 'T1', name: 'T1' },
  { id: 'T1+', name: 'T1+' },
  { id: 'T2', name: 'T2' },
  { id: 'T2+', name: 'T2+' },
  { id: 'T3', name: 'T3' },
  { id: 'T3+', name: 'T3+' },
  { id: 'T4', name: 'T4' },
  { id: 'T4+', name: 'T4+' },
];

// Faction options
export const factions = [
  'Basic',
  'Protection',
  'Leadership',
  'Aggression',
  'Justice',
  'Your Choice',
];

// Primary loot table rolls
export const lootTable = [
  {
    tier: 'T1',
    roll: [
      'None',
      'None',
      'None',
      'None',
      'Tier C Basic',
      'Tier C Basic',
      'Tier C Basic',
      'Tier C Basic',
      'Tier C Basic',
      'Tier C Basic',
      'Tier B Roll',
      'Tier B Roll',
    ],
  },
  {
    tier: 'T1+',
    roll: [
      'None',
      'Tier C Basic',
      'Tier C Basic',
      'Tier C Basic',
      'Tier C Basic',
      'Tier C Basic',
      'Tier C Basic',
      'Tier B Roll',
      'Tier B Roll',
      'Tier B Roll',
      'Tier B Roll',
      'Tier A Roll',
    ],
  },
  {
    tier: 'T2',
    roll: [
      'Tier C Basic',
      'Tier C Basic',
      'Tier C Basic',
      'Tier C Basic',
      'Tier B Roll',
      'Tier B Roll',
      'Tier B Roll',
      'Tier B Roll',
      'Tier B Roll',
      'Tier B Roll',
      'Tier A Roll',
      'Tier A Roll',
    ],
  },
  {
    tier: 'T2+',
    roll: [
      'Tier C Basic',
      'Tier B Roll',
      'Tier B Roll',
      'Tier B Roll',
      'Tier B Roll',
      'Tier B Roll',
      'Tier B Roll',
      'Tier A Roll',
      'Tier A Roll',
      'Tier A Roll',
      'Tier A Roll',
      'Tier S Roll',
    ],
  },
  {
    tier: 'T3',
    roll: [
      'Tier B Roll',
      'Tier B Roll',
      'Tier B Roll',
      'Tier B Roll',
      'Tier A Roll',
      'Tier A Roll',
      'Tier A Roll',
      'Tier A Roll',
      'Tier A Roll',
      'Tier A Roll',
      'Tier S Roll',
      'Tier S Roll',
    ],
  },
  {
    tier: 'T3+',
    roll: [
      'Tier A Roll',
      'Tier A Roll',
      'Tier A Roll',
      'Tier A Roll',
      'Tier A Roll',
      'Tier A Roll',
      'Tier A Roll',
      'Tier A Roll',
      'Tier S Roll',
      'Tier S Roll',
      'Tier S Roll',
      'Tier S Roll',
    ],
  },
  {
    tier: 'T4',
    roll: [
      'Tier A Roll',
      'Tier A Roll',
      'Tier A Roll',
      'Tier A Roll',
      'Tier S Roll',
      'Tier S Roll',
      'Tier S Roll',
      'Tier S Roll',
      'Tier S Roll',
      'Tier S Roll',
      'Tier S Roll',
      'Shawarma',
    ],
  },
  {
    tier: 'T4+',
    roll: [
      'Tier S Roll',
      'Tier S Roll',
      'Tier S Roll',
      'Tier S Roll',
      'Tier S Roll',
      'Tier S Roll',
      'Tier S Roll',
      'Tier S Roll',
      'Tier S Roll',
      'Tier S Roll',
      'Shawarma',
      'Shawarma',
    ],
  },
];
